namespace RFM.Character
{
    public static class StaticData
    {
        public static readonly string[] CharacterNames = new string[]
        {
            "Alex", "Anna", "Michael", "Callum", "Kathryn", "June", 
            "Nicole", "Derek", "Shane", "Antony", "Iain", "Gillian", 
            "Howard", "Diane", "Jean", "Diane", "Sophie", "Rosie", 
            "Hayley", "Vincent", "Lindsey", "Josh", "Liam", "Dean", 
            "Adam", "Deborah", "Amelia", "Roger", "Marie", "Leonard", 
            "Adam", "Stacey", "Charlie", "Charles", "Irene", "Stanley", 
            "Clare", "Martyn", "Marilyn", "Ross", "Amber", "Callum", 
            "Robert", "Harriet", "Thomas", "Joanne", "Marc", "Owen", 
            "Albert", "Aimee", "David", "Irene", "Louis", "Zoe", "Adrian", 
            "Maureen", "Jay", "Ryan", "Neil", "Glen", "Natalie", "Alice", 
            "Rachel", "Abdul", "Rosemary", "Joanne", "Hannah", "Sam", 
            "Kathryn", "Grace", "Alexander", "Kathleen", "Julia", "Donna", 
            "Lindsey", "Benjamin", "Harriet", "Mohammed", "Kayleigh", 
            "Timothy", "Sylvia", "Henry", "Billy", "Dawn", "Ross", "Jordan", 
            "Hilary", "Lorraine", "Sam", "Gerard", "Trevor", "Jacob", "Lucy", 
            "Neil", "Lucy", "Andrew", "Irene", "Hugh", "Callum", "Jenna", "Janet", 
            "Tracey", "Declan", "Emily", "Sharon", "Jack", "Simon", "Bruce", 
            "Mathew", "Bethan", "Dominic", "Lindsey", "Marcus", "Ashley", 
            "Amber", "Elaine", "Gillian", "Declan", "Francesca", "Rhys", 
            "Gregory", "Ashley", "Eric", "Mandy", "Joyce", "Sian", "Bruce", 
            "Eleanor", "Patricia", "Maureen", "Stewart", "Kevin", "June", 
            "Billy", "Guy", "Zoe", "Barbara", "Lesley", "Julie", "Barry", 
            "Kevin", "Jay", "Natalie", "Joanna", "Graham", "Zoe", "Allan", 
            "Emma", "Adam", "Liam", "Damien", "Natalie", "Daniel", "Jemma", 
            "Elliott", "Vincent", "Josh", "Maurice", "Deborah", "Laura", 
            "Helen", "Elliott", "Neil", "Katy", "Carly", "Darren", "Dominic", 
            "Joanne", "Jeffrey", "Amy", "Jack", "Leon", "Mark", "Alison", "Lucy", 
            "Benjamin", "Marilyn", "Stuart", "Emma", "Annette", "Mark", "Abdul", 
            "Phillip", "Dylan", "Carol", "Callum", "Janet", "Natalie", "Alan", 
            "Brandon", "Derek", "Melanie", "Marion", "George", "Emma", "Lynda", 
            "Joan", "Nicola", "Hilary", "Carol", "Bruce", "Dominic", "Oliver", 
            "Callum", "Eleanor", "Marie", "Glen", "Graham", "Geraldine", "Tom", 
            "Clare", "Matthew", "Declan", "Tracy", "Jonathan", "Kerry", "Arthur", 
            "Hayley", "Elizabeth", "Joel", "Ross", "Brett", "Nicholas", "Thomas", 
            "Marie", "Maurice", "Yvonne", "Ruth", "Conor", "Denise", "Victor", 
            "Antony", "Gordon", "Hugh", "Hayley", "Martin", "Heather", "Beth", 
            "Thomas", "Fiona", "Hannah", "Zoe", "Gemma", "Abdul", "Bradley", 
            "Joseph", "Trevor", "Cameron", "Edward", "Stewart", "Gareth", "Tom", 
            "Antony", "Bryan", "Ellie", "Rosie", "Gary", "Dean", "Gordon", "Lynne", 
            "Gail", "Simon", "David", "Hilary", "Alison", "Geraldine", "Mohammed", 
            "Tracy", "Alice", "Jade", "Stanley", "Rosemary", "Paige", "Owen", "Tom", 
            "Glen", "Lynne", "Andrew", "Suzanne", "Bruce", "Glen", "Anna", "Joyce", 
            "Carolyn", "Gemma", "Jake", "Francis", "Ryan", "Callum", "Bruce", "Jason", 
            "Rosemary", "Arthur", "June", "Leonard", "Sylvia", "David", "Karen", 
            "Mandy", "Ben", "Dean", "Joan", "Peter", "Gavin", "Neil", "Henry", 
            "Ellie", "Luke", "Emily", "Thomas", "Marc", "Declan", "Gavin", "Charles", 
            "Susan", "Kenneth", "Thomas", "Susan", "Hazel", "Arthur", "Irene", 
            "Carol", "Neil", "Elizabeth", "Katy", "Victor", "Nigel", "Derek", 
            "Olivia", "Leigh", "Katie", "Adam", "Frank", "Andrea", "Terry", 
            "Hannah", "Mark", "Valerie", "Kimberley", "Kevin", "Scott", "Joseph", 
            "Jill", "Amber", "Gail", "Brandon", "Kyle", "Amy", "Martin", "Bradley", 
            "Julie", "Nicola", "Nicola", "Timothy", "Bethan", "Callum", "Ashleigh", 
            "Sally", "Justin", "Ruth", "Michael", "Diana", "Katy", "Jill", "Mandy", 
            "Danny", "Fiona", "Frances", "Charlie", "Joanna", "Max", "Louise", "Kelly", 
            "Roy", "Francesca", "Donna", "Christopher", "Brian", "Sharon", "Barry", 
            "Zoe", "Leslie", "Sheila", "Jordan", "Judith", "Rosie", "Karen", "Nicola", 
            "Barry", "Amanda", "Keith", "Iain", "Jacob", "Paula", "Andrea", "Henry", 
            "Gary", "Stephanie", "Amy", "Marilyn", "Trevor", "Peter", "Natasha", 
            "Craig", "Elliot", "Deborah", "Kathleen", "Nicole", "Roger", "Leanne", 
            "Gavin", "Michelle", "Adam", "Heather", "Jodie", "Frank", "Leslie", 
            "Kerry", "Helen", "Marilyn", "Kevin", "Bruce", "Rachael", "Allan", 
            "Jack", "Kathleen", "Mohammed", "Glenn", "Martin", "Jennifer", "Aimee", 
            "Lawrence", "Roy", "Frances", "Tracey", "Ryan", "Patricia", "Sandra", 
            "Natalie", "Emma", "Lorraine", "Rebecca", "Adam", "Lynn", "Ricky", 
            "Garry", "Donna", "Rosemary", "Duncan", "Iain", "Declan", "Raymond", 
            "Kirsty", "Patricia", "Sheila", "Jamie", "Callum", "Iain", "Jake", 
            "Alexandra", "Alison", "Eleanor", "Kevin", "Charlotte", "Diana", 
            "Stephen", "Marcus", "Eric", "Declan", "Caroline", "Elizabeth", 
            "Rachael", "Andrea", "Pamela", "Stuart", "Danny", "Michael", "Gillian", 
            "Dorothy", "Anne", "Jane", "Nigel", "Fiona", "Roy", "Jeremy", "Teresa", 
            "Sharon", "Lee", "Hilary", "June", "Liam", "Lawrence", "Nicole", "Stanley", 
            "Bethan", "Phillip", "Amber", "Mandy", "Declan", "Shaun", "Veer", "Tara", 
            "Aaina", "Arnav", "Pranay", "Diya", "Aradhya", "Yuvaan", "Vardaniya", 
            "Romil", "Anvi", "Taimur", "Keya", "Madhav", "Dishani", "Hiran", "Raunak", 
            "Hiran", "Tanya", "Divit", "Miraya", "Yasmin", "Ojas", "Hazel", "Renee", 
            "Zoya", "Lavanya", "Hunar", "Sahil", "Divyansh", "Samiha", "Devansh", 
            "Piya", "Shalv", "Anaya", "Jhanvi", "Divyansh", "Sumer", "Adira", "Saksham", 
            "Manjari", "Navya", "Lagan", "Ishita", "Anvi", "Ahana ", "Elakshi", "Pranay", 
            "Biju", "Zara", "Ira", "Abram", "Divij", "Saira", "Yakshit", "Rhea", 
            "Vardaniya", "Oorja", "Mishti", "Aarav", "Manjari", "Bhamini", "Shamik", 
            "Nirvaan", "Samiha", "Shaan", "Renee", "Chirag", "Kanav", "Jiya", "Madhup", 
            "Nakul", "Zaina", "Hridaan", "Zaina", "Inaaya ", "Alia", "Divij", "Dhanush", 
            "Samar", "Diya", "Ayesha", "Emir", "Romil", "Ishita", "Riaan", "Renee", 
            "Gatik", "Ira", "Shamik", "Hrishita", "Lagan", "Yasmin", "Lavanya", 
            "Ira", "Khushi", "Reyansh", "Ahana ", "Divij", "Kimaya", "Yasmin", 
            "Veer", "Samar", "Kashvi", "Nakul", "Riaan", "Kabir", "Kanav", "Kabir", 
            "Arhaan", "Manjari", "Nirvi", "Pranay", "Anika", "Darshit", "Dhruv", 
            "Parinaaz", "Tanya", "Hansh", "Indrajit", "Armaan", "Dhanush", "Rati", 
            "Hrishita", "Pihu", "Vihaan", "Renee", "Eshani", "Raghav", "Elakshi", 
            "Zoya", "Miraan", "Madhav", "Parinaaz", "Khushi", "Aaina", "Kavya", 
            "Raghav", "Alisha", "Bhamini", "Nitara", "Nayantara", "Rati", "Yashvi", 
            "Taimur", "Dharmajan", "Shaan", "Manjari", "Farhan", "Aradhya", "Khushi", 
            "Mohanlal", "Shamik", "Kanav", "Nirvaan", "Advik", "Sana", "Purab", 
            "Farhan", "Renee", "Madhup", "Umang", "Yashvi", "Jayan", "Shamik", "Aaryahi", 
            "Biju", "Divyansh", "Vardaniya", "Hunar", "Rasha", "Madhup", "Azad", 
            "Kaira", "Myra", "Hazel", "Lavanya", "Pihu", "Devansh", "Anay", "Gatik", 
            "Myra", "Kanav", "Mahika", "Kashvi", "Fateh", "Vihaan", "Divij", "Tushar", 
            "Farhan", "Armaan", "Mahika", "Akarsh", "Kartik", "Kabir", "Saanvi", 
            "Gatik", "Anvi", "Lakshay", "Samiha", "Yasmin", "Biju", "Parinaaz", 
            "Akarsh", "Inaaya ", "Aarna", "Miraya", "Divyansh", "Pranay", "Darshit", 
            "Madhup", "Devansh", "Neelofar", "Romil", "Stuvan", "Adira", "Jivin", 
            "Biju", "Damini", "Anahita", "Arnav", "Kimaya", "Divyansh", "Rati", 
            "Vihaan", "Krish", "Pranay", "Taimur", "Sana", "Anaya", "Jiya", "Jayan", 
            "Rasha", "Pari", "Lagan", "Tiya", "Bhavin", "Vedika", "Parinaaz", "Indranil", 
            "Ishaan", "Shlok", "Eva", "Ojas", "Fateh", "Kimaya", "Ahana ", "Nitya", 
            "Jayant", "Abram", "Anaya", "Pihu", "Yuvraj ", "Jiya", "Diya", "Sahil", 
            "Nehmat", "Taimur", "Vidur", "Nirvi", "Ojas", "Indrans", "Jhanvi", "Prisha", 
            "Abram", "Amira", "Seher", "Dhanush", "Shamik", "Seher", "Azad", "Inaaya ", 
            "Ranbir", "Himmat", "Nakul", "Tarini", "Anya", "Sumer", "Manjari", "Reyansh", 
            "Pari", "Taimur", "Kiara", "Myra", "Miraya", "Hansh", "Saanvi", "Sahil", 
            "Vidur", "Siya", "Zeeshan", "Nehmat", "Dhanush", "Aarav", "Kimaya", "Kartik", 
            "Rasha", "Shamik", "Indranil", "Nakul", "Mamooty", "Navya", "Alia", "Uthkarsh", 
            "Rhea", "Pari", "Jiya", "Zeeshan", "Arhaan", "Yakshit", "Rati", "Jiya", 
            "Aaina", "Trisha", "Nitara", "Rhea", "Azad", "Ivan", "Alia", "Chirag", 
            "Pranay", "Rati", "Indranil", "Alia", "Eva", "Aradhya", "Jhanvi", "Lavanya", 
            "Tanya", "Aarav", "Armaan", "Bhamini", "Shaan", "Sahil", "Anahita", "Badal", 
            "Zoya", "Zoya", "Zeeshan", "Kanav", "Ira", "Myra", "Dharmajan", "Samaira", 
            "Hansh", "Abram", "Yakshit", "Parinaaz", "Zeeshan", "Saksham", "Aarav", 
            "Lakshit", "Abram", "Saanvi", "Tanya", "Aarav", "Pari", "Eva", "Manjari", 
            "Divyansh", "Kanav", "Fateh", "Mahika", "Nehmat", "Kiaan", "Romil", "Ranbir", 
            "Prisha", "Jivin", "Divyansh", "Anika", "Vivaan", "Mishti", "Dhanush", "Akarsh", 
            "Raghav", "Alisha", "Yasmin", "Vritika", "Farhan", "Onkar", "Himmat", 
            "Neysa", "Elakshi", "Nehmat", "Neelofar", "Shray", "Farhan", "Indrans", 
            "Ranbir", "Advik", "Arnav", "Arnav", "Lagan", "Pihu", "Pranay", "Ivana", 
            "Saksham", "Tejas", "Jiya", "Arnav", "Siya", "Rati", "Mahika", "Neysa", 
            "Bhamini", "Riya", "Nayantara", "Amira", "Navya", "Adira", "Umang", "Heer", 
            "Jayesh", "Lakshay", "Uthkarsh", "Khushi", "Riaan", "Aayush", "Hiran", 
            "Indrajit", "Purab", "Shamik", "Shayak", "Vritika", "Tushar", "Saanvi", 
            "Divij", "Shayak", "Vanya", "Miraya", "Armaan", "Arnav", "Purab", "Ishaan", 
            "Indrajit", "Keya", "Riaan", "Taran", "Vivaan", "Ira", "Hansh", "Ritvik", 
            "Farhan", "Anvi", "Sana", "Nakul", "Badal", "Ryan", "Jayesh", "Elakshi", 
            "Samiha", "Devansh", "Romil", "Yuvaan", "Shalv", "Rohan", "Zeeshan", "Emir", 
            "Divyansh", "Jhanvi", "Anya", "Anika", "Shayak", "Yasmin", "Zoya", "Shlok", 
            "Gatik", "Anvi", "Farhan", "Rati", "Charvi", "Aaryahi", "Armaan", "Romil", 
            "Shamik", "Sara", "Piya", "Indrans", "Ivan", "Mishti", "Jivika", "Uthkarsh", 
            "Zara", "Navya", "Dhruv", "Chirag", "Zara", "Dharmajan", "Kiaan", "Siya", 
            "Madhup", "Biju", "Veer", "Aayush", "Divyansh", "Vihaan", "Ivana", "Ela", "Riaan"
        };
    }
}
